version: '3.8'

services:
  web:
    build: .
    ports:
      - "8000:8000"
    environment:
      - TELEGRAM_BOT_TOKEN=your_token_here
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:8000/webhook"]
      interval: 30s
      timeout: 10s
      retries: 3
